[metadata]
name = roborangers
version = 0.0.1

[options]
packages = find:
package_dir = 
  = .

[options.entry_points]
console_scripts =
  centroid_detector_node_trt = roborangers.yolo.centroid_detector_node_trt:main
  yolov8_video_inference = roborangers.opencv.yolov8_video_inference:run
  imx219_yolov8_trt = roborangers.yolo.imx219_yolov8_trt:main
  imx219_yolov8n_trt = roborangers.yolo.imx219_yolov8n_trt:main
