centroid_detector_node:
  ros__parameters:
    model_path: ""
    class_names_path: ""
    target_class_name: "rc_car"

    confidence_threshold: 0.35
    iou_threshold: 0.45
    input_size: 640

    camera_width: 1280
    camera_height: 720
    display_width: 1280
    display_height: 720
    camera_fps: 30
    flip_method: 0

    publish_rate_hz: 20.0
    display: false
    use_cpu: false
